---
- name: Create EC2 instances
  ec2:
    key_name: "{{ key_name }}"
    region: "{{ region_name }}"
    instance_type: "{{ instance_type }}"
    image: "{{ ami_id }}"
    vpc_subnet_id: "{{ random_subnet }}"
    group: "{{ instance_name }}-sg"
    wait: yes
    instance_tags:
      Name: jumpbox
      Env: sandbox
    count_tag: 
      Name: jumpbox
      Env: sandbox
    exact_count: 1
    assign_public_ip: yes
  register: ec2
  
- name: Add the newly created EC2 instance(s) to the local host group
  local_action: lineinfile 
                path="inventory/ec2"
                regexp={{ item.public_ip }} 
                insertafter="[jumpbpox]" line="{{ item.public_ip }} ansible_user=ec2-user ansible_ssh_private_key_file=keys/{{ key_name }}.pem ansible_ssh_extra_args='-o StrictHostKeyChecking=no'"
  with_items: "{{ ec2.instances }}"
